# Generated by Django 4.2.5 on 2023-09-24 10:46

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", autoslug.fields.AutoSlugField(default=None, editable=False, populate_from="company_name")),
                ("email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("rate", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted Proposal", "Submitted Proposal"),
                            ("Applied", "Applied"),
                            ("Meeting Done", "Meeting Done"),
                            ("For Meeting", "For Meeting"),
                            ("No Reply", "No Reply"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField()),
            ],
            options={
                "verbose_name": "tracker",
                "verbose_name_plural": "tracker",
            },
        ),
    ]
